const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const app = fs.readFileSync('public/app.js', 'utf8');
const html = fs.readFileSync('public/index.html', 'utf8');
const styles = fs.readFileSync('public/styles.css', 'utf8');

test('notification settings use autosave instead of a save button', () => {
    assert.doesNotMatch(app, /save-notifications/);
    assert.doesNotMatch(html, /Save notifications/);
    assert.match(html, /notification-save-status/);
    assert.match(app, /notificationsEl\.addEventListener\('change'/);
    assert.match(app, /queueNotificationSave\(600\)/);
});

test('notification autosave preserves the current form and flushes before tests', () => {
    const saveStart = app.indexOf('async function saveNotifications');
    const saveEnd = app.indexOf('function queueNotificationSave', saveStart);
    const saveBody = app.slice(saveStart, saveEnd);

    assert.doesNotMatch(saveBody, /renderNotifications\(\)/);
    assert.match(app, /await flushNotificationSave\(\);[\s\S]*\/api\/notifications\/test/);
    assert.match(app, /window\.addEventListener\('beforeunload'/);
    assert.match(app, /Save failed/);
});

test('ntfy topic setup is generated by the backend and supports sharing and explicit regeneration', () => {
    assert.doesNotMatch(app, /id="notify-ntfy-topic" type="password"/);
    assert.match(app, /Generated automatically when ntfy is enabled/);
    assert.match(app, /data-regenerate-ntfy-topic/);
    assert.match(app, /window\.confirm\('This will replace the current ntfy topic/);
    assert.match(app, /\/api\/notifications\/ntfy\/topic\/regenerate/);
    assert.match(app, /data-send-ntfy-topic/);
    assert.match(app, /notify-ntfy-topic-recipient/);
    assert.match(app, /\/api\/notifications\/ntfy\/topic\/send/);
    assert.match(app, /data-notification-local/);
});


test('schedule editor only shows fields relevant to the selected mode', () => {
    assert.match(html, /id="weekday-wrap">Weekday/);
    assert.match(html, /id="monthday-wrap">Day of month/);
    assert.match(app, /weekday-wrap'\)\.hidden = mode !== 'weekly'/);
    assert.match(app, /monthday-wrap'\)\.hidden = mode !== 'monthly'/);
    assert.match(app, /time-wrap'\)\.hidden = mode === 'advanced'/);
    assert.match(styles, /\[hidden\]\s*\{\s*display:\s*none !important;/);
});

test('cron is generated and read-only outside advanced schedule mode', () => {
    assert.match(app, /cron-wrap'\)\.hidden = false/);
    assert.match(app, /cron'\)\.readOnly = mode !== 'advanced'/);
    assert.match(app, /function updateCronPreview\(\)/);
    assert.match(app, /cron'\)\.value = formToCron\(\)/);
    assert.match(app, /weekday'\)\.addEventListener\('change', updateCronPreview\)/);
    assert.match(app, /monthday'\)\.addEventListener\('input', updateCronPreview\)/);
    assert.match(app, /schedule-time'\)\.addEventListener\('input', updateCronPreview\)/);
});
